<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tirs_foundation"
 *
 * Auto generated by Extension Builder 2016-02-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TIRS Foundation',
	'description' => 'Base layout based on Foundation 6.4.',
	'category' => 'templates',
	'author' => 'Pavel Leonidov',
	'author_email' => 'info@pavel-leonidov.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
			'fluid_styled_content' => '7.6.0-8.7.99',
			'tirs_configuration' => '7.6.0-8.7.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'gridelements' => '7.6.0-8.7.99'
		),
	),
);